### ISSUE TITLE
这个怎么办

### ISSUE THREAD

**Issue by Ghostkill1024** [xiaotianliu01/DQN-with-MCTS-on-Adaptive-Bitrate#1]
C:\Users\Z\Desktop\DQN-with-MCTS-on-Adaptive-Bitrate-main\venv\lib\site-packages\gym\core.py:27: UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+
  "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+"
Traceback (most recent call last):
  File "C:\Users\Z\Desktop\DQN-with-MCTS-on-Adaptive-Bitrate-main\test.py", line 186, in <module>
    main()
  File "C:\Users\Z\Desktop\DQN-with-MCTS-on-Adaptive-Bitrate-main\test.py", line 163, in main
    initial_non_ten, done = env.reset(test_set_path, test_bw_path, train=False)
TypeError: reset() takes 1 positional argument but 3 were given

**Comment by xiaotianliu01** [comment]
代码在我的环境下运行正常，包括你后面的一个问题我感觉都是环境版本问题。我的python版本是3.6.5, gym版本为0.19.0

**Comment by xiaotianliu01** [comment]
> C:\Users\Z\Desktop\DQN-with-MCTS-on-Adaptive-Bitrate-main\venv\lib\site-packages\gym\core.py:27: UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+ "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+" Traceback (most recent call last): File "C:\Users\Z\Desktop\DQN-with-MCTS-on-Adaptive-Bitrate-main\test.py", line 186, in main() File "C:\Users\Z\Desktop\DQN-with-MCTS-on-Adaptive-Bitrate-main\test.py", line 163, in main initial_non_ten, done = env.reset(test_set_path, test_bw_path, train=False) TypeError: reset() takes 1 positional argument but 3 were given

大概率是你的gym版本太高了

**Comment by Ghostkill1024** [comment]
谢谢已经解决
